# Generated by Django 3.1 on 2020-12-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicament',
            new_name='Produit',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='fonction',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='medicament',
            new_name='produit',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cni',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date',
        ),
        migrations.AddField(
            model_name='vente',
            name='paiement',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
