# Generated by Django 3.1 on 2020-12-08 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20201203_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('somme', models.PositiveIntegerField(blank=True, editable=False, verbose_name='à payer')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DetailStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('motif', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somme', models.PositiveIntegerField(default=0, verbose_name='somme payée')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('tel', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='vente',
            name='produit',
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['nom', 'prix']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['produit']},
        ),
        migrations.RemoveField(
            model_name='commande',
            name='description',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='number',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='qté',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='produits',
        ),
        migrations.AddField(
            model_name='commande',
            name='a_payer',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commande',
            name='payee',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='reste',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='tel',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='adresse',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='tel',
            field=models.CharField(max_length=40, null=True, verbose_name='numero de télephone'),
        ),
        migrations.AddField(
            model_name='produit',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='rapport',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stock',
            name='expiration',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='expiration_date',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='produit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.produit'),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantite_actuelle',
            field=models.FloatField(default=None, editable=False, verbose_name='quantité actuelle'),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantite_initiale',
            field=models.FloatField(default=None, verbose_name='quantité initial'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='nom et prenom'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Vente',
        ),
        migrations.AddField(
            model_name='paiement',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.commande'),
        ),
        migrations.AddField(
            model_name='detailstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock'),
        ),
        migrations.AddField(
            model_name='detailcommande',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.commande'),
        ),
        migrations.AddField(
            model_name='stock',
            name='Staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff'),
        ),
    ]
